// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FrontendState {
    /**
     * Creates a new FrontendState instance.
     * @param {Partial<FrontendState>} [$$source = {}] - The source object to create the FrontendState.
     */
    constructor($$source = {}) {
        if (!("modeLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modeLabel"] = "";
        }
        if (!("statusLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusLabel"] = "";
        }
        if (!("remainingText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remainingText"] = "";
        }
        if (!("usageText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["usageText"] = "";
        }
        if (!("detailText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detailText"] = "";
        }
        if (!("updatedText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedText"] = "";
        }
        if (!("tooltip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tooltip"] = "";
        }
        if (!("todayCostText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["todayCostText"] = "";
        }
        if (!("totalCostText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["totalCostText"] = "";
        }
        if (!("todayTokenText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["todayTokenText"] = "";
        }
        if (!("sourceText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceText"] = "";
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("remainingUSD" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["remainingUSD"] = null;
        }
        if (!("lowBalance" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["lowBalance"] = false;
        }
        if (!("unlimited" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unlimited"] = false;
        }
        if (!("hasData" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasData"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("amountText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["amountText"] = "";
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["percent"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("fetching" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fetching"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FrontendState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FrontendState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FrontendState(/** @type {Partial<FrontendState>} */($$parsedSource));
    }
}
