// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function HideWindow() {
    return $Call.ByID(1795100509);
}

/**
 * @returns {$CancellablePromise<$models.FrontendState>}
 */
export function Initial() {
    return $Call.ByID(1501209883).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.FrontendState>}
 */
export function OpenAPIKeyPage() {
    return $Call.ByID(697784617).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(1267591628);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(106530645);
}

/**
 * @returns {$CancellablePromise<$models.FrontendState>}
 */
export function Refresh() {
    return $Call.ByID(2935844652).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} apiKey
 * @returns {$CancellablePromise<$models.FrontendState>}
 */
export function SaveAPIKey(apiKey) {
    return $Call.ByID(761518255, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {boolean} collapsed
 * @returns {$CancellablePromise<void>}
 */
export function SetCollapsed(collapsed) {
    return $Call.ByID(1886259292, collapsed);
}

/**
 * @param {boolean} open
 * @returns {$CancellablePromise<void>}
 */
export function SetSettingsOpen(open) {
    return $Call.ByID(3936976566, open);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ShowMain() {
    return $Call.ByID(843776113);
}

// Private type creation functions
const $$createType0 = $models.FrontendState.createFrom;
